config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/', to: 'home#index', as: :index
  get '/dashboard', to: 'home#dashboard', as: :dashbord
  get '/help', to: 'home#help'
  get '/info', to: 'home#info'
  get '/next_bus', to: 'home#next_bus'
  get '/repair', to: 'home#repair'
  get '/informacoes', to: 'home#list_bus', as: :list_bus
  get '/repair/confirmacao/:problem', to: 'home#repair_confirmation', as: :repair_confirmation
  get '/sucesso/:text', to: 'home#sucesso', as: :sucesso
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Rails.application.routes.url_helpers

  
  NOME_RUA = 'Imaculada Conceição, 1174 - Prado Velho'
  ONIBUS = [
    { name: '050 - INTERBAIRROS V', number: '050', delay: 1 },
    { name: '165 - UNIVERSIDADES', number: '165', delay: 5 },
    { name: '175 - BOM RETIRO / PUC', number: '175', delay: 15 },
    { name: '471 - V. SÃO PAULO', number: '471', delay: 23 },
    { name: '472 - UBERABA', number: '472', delay: 35 },
    { name: '475 - CANAL BELÉM', number: '475', delay: 42 },
    { name: '614 - FAZENDINHA / PUC', number: '614', delay: 26 }
  ]
  
  before_action :load_data

  def index;end

  def dashboard
    render :dashboard, layout: 'dashboard'
  end

  def help;end

  def info
    @number = params[:number]
  end

  def next_bus;end

  def repair;end

  def list_bus;end

  def repair_confirmation
    @protocolo = rand(320..999).to_s.rjust(10, '0')
    @problem = params[:problem]
  end

  def sucesso
    @text = params[:text]
  end

  def load_data
    @spot_name = NOME_RUA
    @list_bus = ONIBUS

    @bus = ONIBUS.detect { |b| b[:number] == params[:number] } if params[:number].present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.erb
<div class="d-flex justify-content-center align-items-center h-100 flex-column">
  <div class="title time-clock mt-4"></div>
  <div class="avatar-logo">
    <img src="logo.png" height="200" width="200" />
  </div>
  <div class="description mb-2" style="text-align: center;">
    Seja bem vindo(a)! <br>
    Escolha em uma das opções:
  </div>
  
  <div class="actions d-flex flex-row justify-content-around w-100 mt-4">
    <div class="item p-4 rounded d-flex justify-content-center flex-column">
      <a href="<%= list_bus_path %>">
        <div class="d-flex justify-content-center">
          <div class="item-avatar rounded-circle d-flex justify-content-center align-items-center"> <i class="fas fa-bus"></i></div>
        </div>
        <span class="mt-2" style="text-align: center;">Informações sobre as linhas</span>
      </a>
    </div>
    <div class="item p-4 rounded d-flex justify-content-center flex-column">
      <a href="<%= next_bus_path %>">
        <div class="d-flex justify-content-center">
          <div class="item-avatar rounded-circle d-flex justify-content-center align-items-center"> <i class="fas fa-clock"></i></div>
        </div>
        <span class="mt-2" style="text-align: center;">Qual próximo ônibus?</span>
      </a>
    </div>
    <div class="item p-4 rounded d-flex justify-content-center flex-column">
      <a href="<%= repair_path %>">
        <div class="d-flex justify-content-center">
          <div class="item-avatar rounded-circle d-flex justify-content-center align-items-center"> <i class="fas fa-tools"></i></div>
        </div>
        <span class="mt-2" style="text-align: center;">Problema no ponto de ônibus?</span>
      </a>
    </div>
  </div >
</div>
<script>
  $(document).ready(function() {
    alertaData();
  })
</script>

app/views/home/index_old.erb
<div class="d-flex justify-content-center align-items-center h-100 flex-column">
  <div class="title time-clock mt-4"></div>
  <div class="avatar-logo">
    <img src="logo.png" height="200" width="200" />
  </div>
  <div class="description mb-2" style="text-align: center;">
    Seja bem vindo(a)! <br>
    Escolha em uma das opções:
  </div>
  
  <div class="actions d-flex flex-row justify-content-around w-100 mt-4">
    <div class="item p-4 rounded d-flex justify-content-center flex-column">
      <a href="<%= help_path %>">
        <div class="d-flex justify-content-center">
          <div class="item-avatar rounded-circle d-flex justify-content-center align-items-center"> <i class="fas fa-volume-up"></i></div>
        </div>
        <span class="mt-2" style="text-align: center;">Mê avisa?</span>
      </a>
    </div>
    <div class="item p-4 rounded d-flex justify-content-center flex-column">
      <a href="<%= list_bus_path %>">
        <div class="d-flex justify-content-center">
          <div class="item-avatar rounded-circle d-flex justify-content-center align-items-center"> <i class="fas fa-bus"></i></div>
        </div>
        <span class="mt-2" style="text-align: center;">Informações sobre as linhas</span>
      </a>
    </div>
    <div class="item p-4 rounded d-flex justify-content-center flex-column">
      <a href="<%= next_bus_path %>">
        <div class="d-flex justify-content-center">
          <div class="item-avatar rounded-circle d-flex justify-content-center align-items-center"> <i class="fas fa-clock"></i></div>
        </div>
        <span class="mt-2" style="text-align: center;">Qual próximo ônibus?</span>
      </a>
    </div>
    <div class="item p-4 rounded d-flex justify-content-center flex-column">
      <a href="<%= repair_path %>">
        <div class="d-flex justify-content-center">
          <div class="item-avatar rounded-circle d-flex justify-content-center align-items-center"> <i class="fas fa-tools"></i></div>
        </div>
        <span class="mt-2" style="text-align: center;">Problema no ponto de ônibus?</span>
      </a>
    </div>
  </div >
</div>

app/views/home/info.erb
<div class="d-flex justify-content-center align-items-center h-100 flex-column">
  <div class="title time-clock mt-4"></div>
  <div class="avatar-logo">
    <img src="logo.png" height="100" width="100" />
  </div>
  <div class="description mb-2" style="text-align: center;">
    Informações de 
    <b><%= @bus[:name] %></b>
  </div>
  <iframe
   style="width: 100%; height: 60vh;"
   src="https://www.urbs.curitiba.pr.gov.br/horario-de-onibus/<%= @number %>"></iframe>

  <a class='btn btn-info btn-back' href="<%= list_bus_path %>"> voltar </a>

</div>

app/views/home/list_bus.erb
<div class="d-flex justify-content-center align-items-center h-100 flex-column">
  <div class="title time-clock mt-4"></div>
  <div class="avatar-logo">
    <img src="logo.png" height="100" width="100" />
  </div>
  <div class="description mb-2" style="text-align: center;">
    Linhas disponiveis no ponto de onibus <br>
    <b><%= @spot_name %></b>
  </div>

  <div class="bus d-flex flex-wrap mt-2 justify-content-center">
    <% @list_bus.each do |bus| %>
      <a href="<%= info_path(number: bus[:number]) %>">
        <div class="bus-item rounded p-2 m-2 d-flex flex-row">
          <span class="bus-text d-flex justify-content-center align-items-center ml-3 mr-3"><%= bus[:name] %></span>
        </div>
      </a>
    <% end %>
  </div> 

  <a class='btn btn-info btn-back' href="<%= index_path %>"> voltar </a>

</div>

app/views/home/list_sound.erb
<div class="d-flex justify-content-center align-items-center h-100 flex-column">
  <div class="title time-clock mt-4"></div>
  <div class="avatar-logo">
    <img src="logo.png" height="100" width="100" />
  </div>
  <div class="description mb-2" style="text-align: center;">
    Qual linha você deseja ser avisado?
  </div>

  <div class="bus d-flex flex-wrap mt-2 justify-content-around">
    <div class="bus-item rounded p-2 m-2 d-flex flex-row">
      <div class="bus-icon d-flex justify-content-center">
        <div class="bus-status more1 rounded-circle d-flex justify-content-center align-items-center">1 min.</div>
      </div>
      <span class="bus-text d-flex justify-content-center align-items-center ml-3 mr-3">Linha 001 - CWB - SP</span>
    </div>
    <div class="bus-item rounded p-2 m-2 d-flex flex-row mt-2">
      <div class="bus-icon d-flex justify-content-center">
        <div class="bus-status more5 rounded-circle d-flex justify-content-center align-items-center">5 min.</div>
      </div>
      <span class="bus-text d-flex justify-content-center align-items-center ml-3 mr-3">Linha 001 - CWB - SP</span>
    </div>
    <div class="bus-item rounded p-2 m-2 d-flex flex-row mt-2">
      <div class="bus-icon d-flex justify-content-center">
        <div class="bus-status more10 rounded-circle d-flex justify-content-center align-items-center">+10 min.</div>
      </div>
      <span class="bus-text d-flex justify-content-center align-items-center ml-3 mr-3">Linha 001 - CWB - SP</span>
    </div>
    <div class="bus-item rounded p-2 m-2 d-flex flex-row mt-2">
      <div class="bus-icon d-flex justify-content-center">
        <div class="bus-status more10 rounded-circle d-flex justify-content-center align-items-center">+10 min.</div>
      </div>
      <span class="bus-text d-flex justify-content-center align-items-center ml-3 mr-3">Linha 001 - CWB - SP</span>
    </div>
    <div class="bus-item rounded p-2 m-2 d-flex flex-row mt-2">
      <div class="bus-icon d-flex justify-content-center">
        <div class="bus-status more10 rounded-circle d-flex justify-content-center align-items-center">+10 min.</div>
      </div>
      <span class="bus-text d-flex justify-content-center align-items-center ml-3 mr-3">Linha 001 - CWB - SP</span>
    </div>
    <div class="bus-item rounded p-2 m-2 d-flex flex-row mt-2">
      <div class="bus-icon d-flex justify-content-center">
        <div class="bus-status more10 rounded-circle d-flex justify-content-center align-items-center">+10 min.</div>
      </div>
      <span class="bus-text d-flex justify-content-center align-items-center ml-3 mr-3">Linha 001 - CWB - SP</span>
    </div>
  </div> 

  <a class='btn btn-info btn-back' href="<%= index_path %>"> voltar </a>

</div>

app/views/home/next_bus.erb
<div class="d-flex justify-content-center align-items-center h-100 flex-column">
  <div class="title time-clock mt-4"></div>
  <div class="avatar-logo">
    <img src="logo.png" height="100" width="100" />
  </div>
  <div class="description mb-2" style="text-align: center;">
    Você está no ponto de ônibus <br>
    <b><%= @spot_name %></b>
  </div>

  <div class="bus d-flex flex-wrap mt-2 justify-content-center">
    <% @list_bus.sort_by { |st| -st[:delay].to_i }.reverse.each do |bus| %>
      <div class="bus-item rounded p-2 m-2 d-flex flex-row">
        <div class="bus-icon d-flex justify-content-center">
          <%if bus[:delay] <= 1%>
            <div class="bus-status more1 rounded-circle d-flex justify-content-center align-items-center"><%= bus[:delay]%> min.</div>
          <%elsif bus[:delay] <= 15 %>
            <div class="bus-status more5 rounded-circle d-flex justify-content-center align-items-center"><%= bus[:delay]%> min.</div>
          <%else%>
            <div class="bus-status more10 rounded-circle d-flex justify-content-center align-items-center">+<%= bus[:delay]%> min.</div>
          <%end%>
        </div>
        <span class="bus-text d-flex justify-content-center align-items-center ml-3 mr-3"><%= bus[:name]%></span>
      </div>
    <% end %>
  </div> 

  <a class='btn btn-info btn-back' href="<%= index_path %>"> voltar </a>

</div>

app/views/home/repair.erb
<div class="d-flex justify-content-center align-items-center h-100 flex-column">
  <div class="title time-clock mt-4"></div>
  <div class="avatar-logo">
    <img src="logo.png" height="100" width="100" />
  </div>
  <div class="description mb-2" style="text-align: center;">
    Você encontrou problemas no ponto de ônibus <br>
    <b><%= @spot_name %></b> ?
  </div>

  <div class="bus d-flex flex-wrap mt-2 justify-content-around">
    <a href="<%= repair_confirmation_path('luz queimada') %>">
      <div class="bus-item rounded p-2 m-2 d-flex flex-row" style='width: 300px;'>
          <div class="bus-icon d-flex justify-content-center">
            <div class="item-avatar rounded-circle d-flex justify-content-center align-items-center"> <i class="fas fa-lightbulb"></i></div>
          </div>
          <span class="bus-text d-flex justify-content-center align-items-center ml-3 mr-3">Luz está queimada!</span>
      </div>
    </a>
    <a href="<%= repair_confirmation_path('lixo cheio') %>">
      <div class="bus-item rounded p-2 m-2 d-flex flex-row mt-2" style='width: 300px;'>
        <div class="bus-icon d-flex justify-content-center">
          <div class="item-avatar rounded-circle d-flex justify-content-center align-items-center"> <i class="fas fa-trash"></i></div>
        </div>
        <span class="bus-text d-flex justify-content-center align-items-center ml-3 mr-3">Lixo está cheio!</span>
      </div>
    </a>
    <a href="<%= repair_confirmation_path('problemas de som') %>">
      <div class="bus-item rounded p-2 m-2 d-flex flex-row mt-2" style='width: 300px;'>
        <div class="bus-icon d-flex justify-content-center">
          <div class="item-avatar rounded-circle d-flex justify-content-center align-items-center"> <i class="fas fa-volume-up"></i></div>
        </div>
        <span class="bus-text d-flex justify-content-center align-items-center ml-3 mr-3">Problemas de som!</span>
    </div>
    </a>
    <a href="<%= repair_confirmation_path('outros problemas') %>">
      <div class="bus-item rounded p-2 m-2 d-flex flex-row mt-2" style='width: 300px;'>
        <div class="bus-icon d-flex justify-content-center">
          <div class="item-avatar rounded-circle d-flex justify-content-center align-items-center"> <i class="fas fa-cog"></i></div>
        </div>
        <span class="bus-text d-flex justify-content-center align-items-center ml-3 mr-3">outros problemas!</span>
      </div>
    </a>
  </div> 

  <a class='btn btn-info btn-back' href="<%= index_path %>"> voltar </a>

</div>

app/views/home/repair_confirmation.erb
<div class="d-flex justify-content-center align-items-center h-100 flex-column">
  <div class="title time-clock mt-4"></div>
  <div class="avatar-logo">
    <img src="/logo.png" height="100" width="100" />
  </div>
  <div class="description mb-2" style="text-align: center;">
    Você está protocolando <br>
    <b><%=@problem  %></b>
  </div>

  <div class="form-wrapper p-4 rounded d-flex flex-column mt-4 mb-4">
    <label style="font-weight: 700; text-align: center;">Qual o seu seu CPF?</label>
    <input class='form-control mt-2' type="text" placeholder="000.000.000-00" />
  </div>
  
  <a class='btn btn-info btn-confirm' href="<%= sucesso_path(text: "Seu número de protocolo é: <b>#{@protocolo}</b>") %>"> confirmar </a>

  <a class='btn btn-info btn-back' href="<%= repair_path %>"> voltar </a>

</div>

app/views/home/sucesso.erb
<div class="d-flex justify-content-center align-items-center h-100 flex-column">
  <div class="title time-clock mt-4"></div>

  <div class="status d-flex justify-content-center" style='margin-top: 20vh;'>
    <i class="fas fa-check-circle"></i>
  </div>

  <div class="description mt-2" style="text-align: center;">
    Tudo certo! <br>
    <%= raw @text %>
  </div>

  
  <a class='btn btn-info btn-back' style='margin-top: 20vh' href="<%= index_path %>"> inicio </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartMobi - Painel Inteligente</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="referrer" content="no-referrer">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <audio class='d-none' controls id="tts-audio"/>
  </body>

  <%= yield :javascripts %>

  <script>
    var alert_sound = undefined
    var alert_sound_2 = undefined
    function formatDate(date) {
        var str =
            ("00" + (date.getDate())).slice(-2)
            + "/" + ("00" + date.getMonth() + 1).slice(-2)
            + "/" + date.getFullYear() + " "
            + " - "
            + ("00" + date.getHours()).slice(-2) + ":"
            + ("00" + date.getMinutes()).slice(-2)
            + ":" + ("00" + date.getSeconds()).slice(-2);
        
      
      return str;
    }

    function googlePlay(text)
    {
      text = encodeURI(text)
      lang = 'pt-br'
          // Get the audio element
      const audioEl = document.getElementById('tts-audio');

      const url= `https://translate.google.com/translate_tts?ie=UTF-8&tl=${lang}&client=tw-ob&q=${text}`;

      // add the sound to the audio element
      audioEl.src = url;

      //For auto playing the sound
      audioEl.play();
    }

    function alertaData()
    {
      var randomNumber = Math.random() * 30;
      if(randomNumber < 5)
      {
        var texto = 'Aviso! 050 - INTERBAIRROS V está chegando em 1 minuto'
        googlePlay(texto);
      }
      else if (randomNumber < 10)
      {
        var texto = 'Aviso! 165 - UNIVERSIDADES está chegando em 5 minuto'
        googlePlay(texto);
      } else if (randomNumber < 15) {
        var texto = 'Aviso! 175 - BOM RETIRO / PUC está chegando em 15 minuto'
        googlePlay(texto);
      }
      
    }

    function updateTime()
    {
      dateNow = new Date()
      $(".time-clock").html(formatDate(dateNow));

      setTimeout(() => {
        updateTime();
      }, 1000);
    }

    $(document).ready(function() {
      $(".title").click();
      updateTime();
    })
  </script>
</html>

app/views/layouts/dashboard.html.erb
<html>
	<head>
    <title>SmartMobi - Painel</title>
		<style>
		
body{
	background-color: #609B28;
}
		
td {
  text-align: center;
}

h1 {
  color: maroon;
  margin-left: 40px;
}

img{
	position: relative;
	width: 280px;
	height: 280px;

}
h2{
	font-family: "Bahnschrift";
	font-size: 48px;
	top: 100px;
	left: 15px;
	position: relative;
	color: #FFFFFF;
	text-align: center;
	padding: 0;
	margin: 0;
}

th{
	font-family: "Bahnschrift";
	font-size: 28px;
	color: #E0DBDB;
}
td{
	font-family: "Bahnschrift Condensed";
	font-size: 22px;
	color: #FFFFFF;
}
iframe{
	position: relative;
	border: 0;
}

table{
	position: relative;
	left: -30px;
}

.level1{
	color: #FFFFFF;
}

.level2{
	color: yellow;
}

.level3{
	color: orange;
}

.level4{
	color: red;
}

</style>
	</head>
	<body style="display: flex">
		
		<div style="display: flex; flex-direction: column">
		<img src="/logo.png" style="display: flex; flex-direction: column"></img>
		 <iframe src='https://lab.onesaitplatform.com/controlpanel/viewers/view/75065b06-08a6-44c2-b647-4be221425493' allowfullscreen width = '720' height = '450'></iframe>
		 </div>
		 <div style="display: flex; flex-direction: column; left: -10px">
		 
		 
		 <h2>Total de usuários no dia de hoje:</h2>
		<h2>15562 usuários</h2>
		 
		 		 
		 <table style="position: relative; left: 15px; top: 300px">
			<tr>
				<th>
					Status
				</th>
				<th>
					Número de Pontos
				</th>
			</tr>
			<tr>
				<td class="level1">
					Normal
				</td>
				<td class="level1">
					775
				</td>
			</tr>
			<tr>
				<td class="level2">
					Precisa de Limpeza
				</td>
				<td class="level2">
					374
				</td>	
			</tr>
			<tr>
				<td class="level3">
					Precisa de Manutenção
				</td>
				<td class="level3">
					250
				</td>
			</tr>
			<tr>				
				<td class="level4">
					Problema com conexão
				</td>
				<td class="level4">
					121
				</td>
			</tr>
		 </table>
		 </div>
	</body>
</html>